language: python
python:
 - "2.7"
 - "3.6"
addons:
  apt:
    packages:
    - golang
before_install:
 - export GOPATH=~/go
 - go get github.com/BurntSushi/toml-test
install:
 - python setup.py install
 - chmod +x ./tests/*.sh
script:
 - ~/go/bin/toml-test ./tests/decoding_test.sh
