[test]
{coucou = "Salut toi"}

[testarray]
#test = {a = "This, is", b = "a, test" }
a = "Yolo, aiuenrst"
points = [ { x = 1, y = 2, z = 3 },
	{ x = 7, y = 8, z = 9 },
	{ x = 2, y = 4, z = 8 } ]
	
my_points = [ { x = 1, y = 2, z = 3 }, { x = 7, y = 8, z = 9 }, { x = 2, y = 4, z = 8 } ]
